meteo/urls.py
from django.conf.urls import url

from . import views

app_name = 'meteo'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<time_delta>month)$', views.index, name='month'),
    url(r'^(?P<time_delta>day)$', views.index, name='day'),
    url(r'^(?P<time_delta>hour)$', views.index, name='hour')
]

myhouse/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^meteo/', include('meteo.urls', namespace='meteo')),
    url(r'^admin/', admin.site.urls),
]

meteo/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models


class Meteo(models.Model):
    id = models.BigAutoField(primary_key=True)
    pressure = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    temperature = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    humidity = models.IntegerField(blank=True, null=True)
    processed_dttm = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'meteo'

    def __str__(self):
        return '{0} ℃, {1} mmHg, {2} %'.format(self.temperature, self.pressure, self.humidity)

meteo/views.py
from datetime import timedelta

from django.db.models import Avg
from django.db.models.functions import TruncHour, TruncMinute, TruncDay
from django.shortcuts import render
from django.utils import timezone

import pygal
from pygal.style import Style

from meteo.models import Meteo
from utils.dbfunctions import Round
from utils.enums import TimePointEnum


def index(request, time_delta='day'):
    meteo_data, time_format = get_meteo_data(time_delta)

    temperature_chart = get_chart_data_uri(meteo_data,
                                           time_format,
                                           data_key='temperature',
                                           data_label='Температура',
                                           y_range=(15, 35),
                                           x_label_key='time_point')

    pressure_chart = get_chart_data_uri(meteo_data,
                                        time_format,
                                        data_key='pressure',
                                        data_label='Давление',
                                        y_range=(730, 760),
                                        x_label_key='time_point',
                                        color='saddleBrown')

    humidity_chart = get_chart_data_uri(meteo_data,
                                        time_format,
                                        data_key='humidity',
                                        data_label='Влажность',
                                        y_range=(20, 90),
                                        x_label_key='time_point',
                                        color='blue')

    try:
        cur_meteo_data = Meteo.objects.order_by("-id")[0]
    except IndexError:
        cur_meteo_data = None

    context = {
        'temperature_chart': temperature_chart,
        'pressure_chart': pressure_chart,
        'humidity_chart': humidity_chart,
        'cur_meteo_data': cur_meteo_data,
    }
    return render(request, 'meteo/index.html', context)


def get_meteo_data(time_delta):
    """Returns meteo data and time_format for specified time_delta."""

    if TimePointEnum.MONTH.equals_to_str(time_delta):
        point_ago = timezone.localtime(timezone.now())
        point_ago = point_ago.replace(
            year=point_ago.year if point_ago.month > 1 else point_ago.year - 1,
            month=point_ago.month - 1 if point_ago.month > 1 else 12
        )

        cur_sub_point = timezone.localtime(timezone.now()).day
        time_format = '%d.%m.%Y'

        # Last month data grouped by day.
        meteo_data = Meteo.objects.filter(processed_dttm__gte=point_ago) \
            .exclude(processed_dttm__day=cur_sub_point) \
            .values(time_point=TruncDay('processed_dttm')) \
            .annotate(temperature=Round(Avg('temperature'), 2),
                      pressure=Round(Avg('pressure'), 2),
                      humidity=Round(Avg('humidity'), 0)) \
            .order_by('time_point')

    elif TimePointEnum.DAY.equals_to_str(time_delta):
        point_ago = timezone.localtime(timezone.now()) - timedelta(days=1)
        cur_sub_point = timezone.localtime(timezone.now()).hour
        time_format = '%d.%m - %H:00'

        # Last day data grouped by hour.
        meteo_data = Meteo.objects.filter(processed_dttm__gte=point_ago) \
            .exclude(processed_dttm__hour=cur_sub_point) \
            .values(time_point=TruncHour('processed_dttm')) \
            .annotate(temperature=Round(Avg('temperature'), 2),
                      pressure=Round(Avg('pressure'), 2),
                      humidity=Round(Avg('humidity'), 0)) \
            .order_by('time_point')

    elif TimePointEnum.HOUR.equals_to_str(time_delta):
        point_ago = timezone.localtime(timezone.now()) - timedelta(hours=1)
        cur_sub_point = timezone.localtime(timezone.now()).minute
        time_format = '%H:%M:%S'

        # Last hour data grouped by minute.
        meteo_data = Meteo.objects.filter(processed_dttm__gte=point_ago) \
            .exclude(processed_dttm__minute=cur_sub_point) \
            .values(time_point=TruncMinute('processed_dttm')) \
            .annotate(temperature=Round(Avg('temperature'), 2),
                      pressure=Round(Avg('pressure'), 2),
                      humidity=Round(Avg('humidity'), 0)) \
            .order_by('time_point')
    else:
        raise ValueError('Invalid time interval passed!')

    return meteo_data, time_format


def get_chart_data_uri(meteo_data,
                       time_format,
                       data_key,
                       data_label,
                       y_range,
                       x_label_key,
                       x_label_rotation=45,
                       color='red'):
    style = Style(colors=(color,),
                  tooltip_font_size=18,
                  label_font_size=14,
                  major_label_font_size=14,
                  legend_font_size=16)

    chart = pygal.Line(range=y_range,
                       x_label_rotation=x_label_rotation,
                       style=style,
                       x_labels_major_every=2,
                       show_minor_x_labels=False)
    chart.x_labels = [d[x_label_key].strftime(time_format) for d in meteo_data]
    chart.add(data_label, [d[data_key] for d in meteo_data])
    return chart.render_data_uri()

meteo/templates/meteo/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}My amazing site{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'meteo/css/style.css' %}" />
    <link rel="shortcut icon" type="image/png" href="{% static 'meteo/images/favicon.ico' %}"/>
    {% block scripts %}{% endblock %}
</head>
<body>

<div id="header"><h1 id="header-caption">Домашняя станция</h1></div>
<div id="content">
    {% block content %}{% endblock %}
</div>
<div id="footer"></div>

</body>
</html>

meteo/templates/meteo/index.html
{% extends "meteo/base.html" %}
{% load static %}

{% block title %}График погоды{% endblock %}

{% block scripts %}
    <script type="text/javascript" src="{% static 'meteo/scripts/tab-controller.js' %}"></script>
    <script type="text/javascript">
        function showDefaultTab() {
            document.getElementById("defaultOpen").click();
        }
        window.onload = showDefaultTab;
    </script>
{% endblock %}

{% block content %}

    {% url 'meteo:hour' 'hour' as hour_view %}
    {% url 'meteo:day' 'day' as day_view %}
    {% url 'meteo:month' 'month' as month_view %}

    <div class="charts">
        <div class="tab">
            <button class="{% if request.path == hour_view %}active{% endif %}"
                    onclick="location.href='{{ hour_view }}';">Данные за час
            </button>

            <button class="{% if request.path == day_view %}active{% endif %}"
                    onclick="location.href='{{ day_view }}';">Данные за день
            </button>
            <button class="{% if request.path == month_view %}active{% endif %}"
                    onclick="location.href='{{ month_view }}';">Данные за месяц
            </button>
        </div>
        <br/>
        <div class="tab">
            <button id="defaultOpen" class="tablinks" onclick="openChart(event, 'temperature')">Температура</button>
            <button class="tablinks" onclick="openChart(event, 'pressure')">Давление</button>
            <button class="tablinks" onclick="openChart(event, 'humidity')">Влажность</button>
        </div>

        <!-- Don't forget the "|safe"! -->
        <div id="temperature" class="tabcontent">
            <embed type="image/svg+xml" src={{ temperature_chart|safe }} height="525" width="700"/>
        </div>


        <div id="pressure" class="tabcontent">
            <embed type="image/svg+xml" src={{ pressure_chart|safe }} height="525" width="700"/>
        </div>

        <div id="humidity" class="tabcontent">
            <embed type="image/svg+xml" src={{ humidity_chart|safe }} height="525" width="700"/>
        </div>
    </div>

    <div class="data">
        <table id="meteo-table">
            <tbody>
            <tr>
                <th colspan="3" class="mainheader">Текущие показатели</th>
            </tr>
            <tr>
                <th>Температура</th>
                <th>Давление</th>
                <th>Влажность</th>
            </tr>
            <tr>
                {% if cur_meteo_data %}
                    <td>{{ cur_meteo_data.temperature }} ℃</td>
                    <td>{{ cur_meteo_data.pressure }} мм рт. ст.</td>
                    <td>{{ cur_meteo_data.humidity }} %</td>
                {% else %}
                    <td></td>
                    <td></td>
                    <td></td>
                {% endif %}
            </tr>
            </tbody>
        </table>
    </div>
{% endblock %}